query entries($username: String, $completedAt: FuzzyDateInt = 10000000) {
	MediaListCollection(userName: $username, type: ANIME, status: COMPLETED, completedAt_greater: $completedAt) {
		lists {
			entries {
				completedAt {
          year
          month
          day
        }
				score(format: POINT_10_DECIMAL)
				media {
					id
					title {
						romaji
						english
						native
						userPreferred
					}
					format
					season
					seasonYear
					genres
					episodes
					duration
					isFavourite
					studios(isMain: true) {
						edges {
							isMain
							node {
								name
								siteUrl
							}
						}
					}
					externalLinks {
						language
						color
						site
						url
					}
					trailer {
						id
						site
						thumbnail
					}
					rankings {
						allTime
						type
						rank
					}
					favourites
					averageScore
					description
					siteUrl
					coverImage {
						medium
						large
						extraLarge
					}
					startDate {
						year
						month
						day
					}
					relations {
						edges {
							node {
								id
								title {
									romaji
									english
									native
									userPreferred
								}
								format
								episodes
								source
								startDate {
									year
									month
									day
								}
							}
							relationType
						}
					}
					status
					siteUrl
				}
			}
		}
	}
}
