query entries($username: String) {
    MediaListCollection(userName: $username, type: ANIME) {
        lists {
            entries {
                score(format: POINT_10_DECIMAL)
                media {
                    id
                    title {
                        romaji
                        english
                        userPreferred
                    }
                    format
                    season
                    seasonYear
                    genres
                    isFavourite
                    studios(isMain: true) {
                        edges {
                            isMain
                            node {
                                name
                                siteUrl
                            }
                        }
                    }
                    streamingEpisodes {
                        site
                    }
                    trailer {
                        site
                        thumbnail
                    }
                    rankings {
                        allTime
                        type
                        rank
                    }
                    favourites
                    averageScore
                    description
                    siteUrl
                    coverImage {
                        medium
                        large
                        extraLarge
                    }
                    relations {
                        edges {
                            relationType
                        }
                    }
                    status
                    siteUrl
                }
            }
        }
    }
}