query media($id: Int, $isAdult: Boolean = false) {
	Media(id: $id, type: ANIME, isAdult: $isAdult) {
		id
		title {
			romaji
			english
			native
			userPreferred
		}
		format
		season
		seasonYear
		genres
		episodes
		duration
		isFavourite
		studios(isMain: true) {
			edges {
				isMain
				node {
					name
					siteUrl
				}
			}
		}
		externalLinks {
			language
			color
			site
			url
		}
		trailer {
			id
			site
			thumbnail
		}
		rankings {
			allTime
			type
			rank
		}
		favourites
		averageScore
		description
		siteUrl
		coverImage {
			medium
			large
			extraLarge
		}
		startDate {
			year
			month
			day
		}
		relations {
			edges {
				node {
					id
					title {
						romaji
						english
						native
						userPreferred
					}
					format
					episodes
					source
					startDate {
						year
						month
						day
					}
				}
				relationType
			}
		}
		status
		siteUrl
	}
}
